FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config libtool sqlite3 libconfig-dev libsqlite3-dev autoconf xsltproc libbsd-dev

COPY . /repo
WORKDIR /repo
RUN autoreconf -fi
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libmysqlclient-dev
RUN ./configure --enable-sqlite3 --enable-mysql
RUN make -j8
RUN make install
RUN make postinstall
RUN /repo/src/cvechecker -i
